name: Pull request

on:
  pull_request:
    branches: 
      - main

jobs:
  build:
    name: PR build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Clean
      run: dotnet clean ./Frustration/Frustration.sln --configuration Release && dotnet nuget locals all --clear

    - name: Restore
      run: dotnet restore ./Frustration/Frustration.sln --configuration Release

    - name: Build
      run: dotnet build ./Frustration/Frustration.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test ./Frustration/Frustration.sln --configuration Release --no-restore --no-build